# Build script for creating a standalone executable of the FastAPI backend

# Ensure PyInstaller is installed
$pyInstallerInstalled = pip show pyinstaller
if (-not $pyInstallerInstalled) {
    Write-Host "Installing PyInstaller..."
    pip install pyinstaller
}

# Clean up previous builds
if (Test-Path "dist") {
    Remove-Item -Recurse -Force dist
}
if (Test-Path "build") {
    Remove-Item -Recurse -Force build
}
if (Test-Path "__pycache__") {
    Remove-Item -Recurse -Force __pycache__
}

# Create a version file
$version = "1.0.0"
$versionContent = @"
# This file is auto-generated by build_exe.ps1
__version__ = "$version"
"@
Set-Content -Path "version.txt" -Value $versionContent

# Run PyInstaller with the spec file
Write-Host "Building executable with PyInstaller..."
pyinstaller --clean --noconfirm pyinstaller.spec

# Set the distribution directory
$distDir = "dist/report_generator_backend"

# Create the main distribution directory if it doesn't exist
if (-not (Test-Path $distDir)) {
    New-Item -ItemType Directory -Force -Path $distDir | Out-Null
}

# Function to safely copy directory if it exists
function Copy-IfExists {
    param (
        [string]$source,
        [string]$destination
    )
    
    if (Test-Path $source) {
        $parentDir = [System.IO.Path]::GetDirectoryName($destination)
        if (-not (Test-Path $parentDir)) {
            New-Item -ItemType Directory -Force -Path $parentDir | Out-Null
        }
        Copy-Item -Path $source -Destination $destination -Recurse -Force -ErrorAction SilentlyContinue
    }
}

# Copy only the directories that exist
Copy-IfExists -source "backend/data" -destination "$distDir/backend/data"
Copy-IfExists -source "backend/ollama_models" -destination "$distDir/backend/ollama_models"
Copy-IfExists -source "backend/database" -destination "$distDir/backend/database"

# Create a run script for Windows
$runScript = @"
@echo off
setlocal

:: Set the current directory to the script's directory
cd /d "%~dp0"

:: Run the application
start "" "%~dp0report_generator_backend.exe"
"@

Set-Content -Path "$distDir/Run Backend.bat" -Value $runScript -Encoding ASCII

Write-Host "`nBuild complete! Executable is available in: $((Resolve-Path $distDir).Path)"
Write-Host "To run the application, execute: 'Run Backend.bat' in the dist directory"
