#!/usr/bin/env bash
# Build script for creating a standalone executable of the FastAPI backend.
# macOS/Linux twin of build_exe.ps1 — keep the two in sync.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

# Ensure PyInstaller is installed
if ! python3 -m pip show pyinstaller >/dev/null 2>&1; then
    echo "Installing PyInstaller..."
    python3 -m pip install pyinstaller
fi

# Clean up previous builds
rm -rf dist build __pycache__

# Create a version file
version="1.0.0"
cat > version.txt <<EOF
# This file is auto-generated by build_exe.sh
__version__ = "$version"
EOF

# Run PyInstaller with the spec file
echo "Building executable with PyInstaller..."
python3 -m PyInstaller --clean --noconfirm pyinstaller.spec

# PyInstaller (onefile mode, per pyinstaller.spec) emits a single file at
# dist/report_generator_backend with no extension on macOS/Linux — the same
# path electron-builder expects to find as a DIRECTORY. Move the file aside
# before creating the directory; mkdir on a path that's already a file fails.
dist_dir="dist/report_generator_backend"
if [ -f "dist/report_generator_backend" ]; then
    mv "dist/report_generator_backend" "dist/report_generator_backend.bin"
    mkdir -p "$dist_dir"
    mv "dist/report_generator_backend.bin" "$dist_dir/report_generator_backend"
elif [ -f "$dist_dir/report_generator_backend" ]; then
    : # already in the expected layout
else
    echo "Backend executable not found after PyInstaller build." >&2
    ls -la dist || true
    exit 1
fi
chmod +x "$dist_dir/report_generator_backend"

# Copy only the directories that exist
copy_if_exists() {
    local source="$1" destination="$2"
    if [ -e "$source" ]; then
        mkdir -p "$(dirname "$destination")"
        cp -Rf "$source" "$destination"
    fi
}

copy_if_exists "backend/data" "$dist_dir/backend/data"
copy_if_exists "backend/ollama_models" "$dist_dir/backend/ollama_models"
copy_if_exists "backend/database" "$dist_dir/backend/database"
copy_if_exists "backend/templates" "$dist_dir/backend/templates"

echo ""
echo "Build complete! Executable is available in: $(cd "$dist_dir" && pwd)"
echo "To run the application, execute: ./report_generator_backend in the dist directory"
